# Replays a sequence of key inputs from a file generated by keyStrokeLogger.py
import keyboard
import time

'''
Parses one line from a keylog into key and duration
'''
def parseline(line: str):
    i = 0
    key = ""
    duration = ""
    while line[i] != ':':
        key += line[i]
        i += 1
    i += 2
    while line[i] != 's':
        duration += line[i]
        i += 1
    duration = float(duration)
    return key, duration

if __name__ == "__main__":
    replay_file = input("Enter the name of the keylog file you wish to replay:\n" )
    num_replays = int(input("Enter the desired number of consecutive replays:\n"))

    print("Replaying beginning in 3")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("1")
    time.sleep(1)

    for _ in range(num_replays):
        with open(replay_file, "r") as f:
            for line in f:
                key, duration = parseline(line)
                if key == 'sleep':
                    time.sleep(duration)
                else:
                    keyboard.press(key)
                    time.sleep(duration)
                    keyboard.release(key)
